<?php get_header(); ?>

<?php
   while( have_posts() ) {
      the_post(); ?>
      <div class="page-banner">
         <div class="page-banner__bg-image"
            style="background-image: url(<?php echo get_theme_file_uri( '/images/ocean.jpg' ); ?>);"></div>
         <div class="page-banner__content container container--narrow">
            <h1 class="page-banner__title"><?php the_title(); ?></h1>
            <div class="page-banner__intro">
               <p>DON'T FORGET TO MAKE MY DYNAMTIC LATOR ON!</p>
            </div>
         </div>
      </div>

      <div class="container container--narrow page-section">
         <div class="metabox metabox--position-up metabox--with-home-link">
            <p><a class="metabox__blog-home-link" href="<?php echo get_post_type_archive_link( 'program' ); ?>"><i class="fa fa-home" aria-hidden="true"></i> All Programs</a>
               <span class="metabox__main"><?php the_title(); ?></span></p>
         </div>

         <div class="generic-content"><?php the_content(); ?></div>

         <!-- Linking upcoming events to viewed program, but without creating another 'Related Events' custom field group, use front-page.php already built custom query -->
         <?php
          $today = date( 'Ymd' );
          $homePageEvents = new WP_Query( array(
            'post_type' => 'event',
            'posts_per_page' => 2, // -1 show all posts
            'meta_key' => 'event_date',
            // [title, post_date, rand for ajax idea] // -1 for all posts
            'orderby' => 'meta_value_num',
            'order' => 'ASC', // DESC, ASC
            'meta_query' => array(
              // Think of array as a filter that returns something you specifiy
              // Only show events that are greater than today date
              array(
                'key' => 'event_date',
                'compare' => '>=',
                'value' => $today,
                'type' => 'numeric'
              ),
              array(
                 'key' => 'related_programs',
                 'compare' => 'LIKE',
                 'value' => '"' . get_the_ID() . '"' // give the id of '12', not 12
              )
            )
          ) );

          if ( $homePageEvents -> have_posts() ) {
            echo '<hr class="section-break">';
            echo '<h2 class="headline headline--medium">Upcoming ' . get_the_title() . ' Events</h2>';

            while ( $homePageEvents->have_posts() ) {
              $homePageEvents->the_post(); ?>
              <!-- <li><?php the_title(); ?></li> -->
              <div class="event-summary">
                <a class="event-summary__date t-center" href="<?php the_permalink(); ?>">
                  <span class="event-summary__month"><?php
                    // the_field( 'event_date' ); // prints full date
                    $eventDate = new DateTime( get_field( 'event_date' ) );
                    echo $eventDate->format( 'M' );
                  ?></span>
                  <span class="event-summary__day"><?php echo $eventDate->format( 'd' ); ?></span>
                </a>
                <div class="event-summary__content">
                  <h5 class="event-summary__title headline headline--tiny"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h5>
                  <p><?php if ( has_excerpt() ) {
                      // the_excerpt(); // style generated by wordpress
                      echo get_the_excerpt(); // follow our style
                    } else {
                      echo wp_trim_words( get_the_content(), 18 );
                    } ?>
                    <a href="<?php the_permalink(); ?>" class="nu gray">Learn more</a></p>
                </div>
              </div>

            <?php }
          }
            wp_reset_postdata();
        ?>
      </div>

   <?php }
?>

<?php get_footer(); ?>